/**
 * @file Mock data store for BringIT (CUET Campus Delivery Network)
 * Provides rich, campus-grounded initial state with interactive local persistence.
 */

export const INITIAL_USERS = [
  {
    id: 'usr-101',
    name: 'Tanvir Rahman',
    email: 'u1904001@student.cuet.ac.bd',
    studentId: '1904001',
    department: 'CSE',
    batch: "'19",
    hall: 'Dr. Qudrat-E-Khuda Hall',
    phone: '01711223344',
    rating: 4.9,
    totalRatings: 38,
    deliveriesCompleted: 42,
    requestsPosted: 12,
    totalEarnings: 3450,
    badges: ['Top Deliverer', '5-Star Hero', 'Elite Traveler'],
    bookmarkedRequests: ['req-002', 'req-005'],
    createdAt: '2024-01-15T08:30:00.000Z',
  },
  {
    id: 'usr-102',
    name: 'Abrar Zayad',
    email: 'u2004052@student.cuet.ac.bd',
    studentId: '2004052',
    department: 'CSE',
    batch: "'20",
    hall: 'Shahid Tareq Huda Hall',
    phone: '01822334455',
    rating: 4.8,
    totalRatings: 26,
    deliveriesCompleted: 31,
    requestsPosted: 18,
    totalEarnings: 2780,
    badges: ['Quick Courier', 'Reliable', 'Top Deliverer'],
    bookmarkedRequests: ['req-001'],
    createdAt: '2024-02-10T11:20:00.000Z',
  },
  {
    id: 'usr-103',
    name: 'Nusrat Jahan',
    email: 'u2108015@student.cuet.ac.bd',
    studentId: '2108015',
    department: 'EEE',
    batch: "'21",
    hall: 'Sufia Kamal Hall',
    phone: '01933445566',
    rating: 5.0,
    totalRatings: 19,
    deliveriesCompleted: 22,
    requestsPosted: 8,
    totalEarnings: 1920,
    badges: ['5-Star Hero', 'Reliable'],
    bookmarkedRequests: [],
    createdAt: '2024-03-01T14:45:00.000Z',
  },
  {
    id: 'usr-104',
    name: 'Mahfuzur Rahman',
    email: 'u2001020@student.cuet.ac.bd',
    studentId: '2001020',
    department: 'CE',
    batch: "'20",
    hall: 'Shahid Abu Saeed Hall',
    phone: '01644556677',
    rating: 4.7,
    totalRatings: 15,
    deliveriesCompleted: 18,
    requestsPosted: 15,
    totalEarnings: 1450,
    badges: ['Reliable'],
    bookmarkedRequests: [],
    createdAt: '2024-03-12T09:15:00.000Z',
  },
  {
    id: 'usr-105',
    name: 'Samiul Alim',
    email: 'u2202045@student.cuet.ac.bd',
    studentId: '2202045',
    department: 'ME',
    batch: "'22",
    hall: 'Kabi Kazi Nazrul Islam Hall',
    phone: '01555667788',
    rating: 4.6,
    totalRatings: 10,
    deliveriesCompleted: 12,
    requestsPosted: 9,
    totalEarnings: 980,
    badges: ['Quick Courier'],
    bookmarkedRequests: [],
    createdAt: '2024-04-05T16:30:00.000Z',
  },
  {
    id: 'usr-106',
    name: 'Sadia Afroz',
    email: 'u2104088@student.cuet.ac.bd',
    studentId: '2104088',
    department: 'CSE',
    batch: "'21",
    hall: 'Sufia Kamal Hall',
    phone: '01799887766',
    rating: 4.9,
    totalRatings: 9,
    deliveriesCompleted: 9,
    requestsPosted: 14,
    totalEarnings: 750,
    badges: ['Campus Novice'],
    bookmarkedRequests: [],
    createdAt: '2024-05-18T12:00:00.000Z',
  },
  {
    id: 'usr-107',
    name: 'Kazi Farhan',
    email: 'u2206012@student.cuet.ac.bd',
    studentId: '2206012',
    department: 'ECE',
    batch: "'22",
    hall: 'Muktijoddha Hall',
    phone: '01811992288',
    rating: 4.8,
    totalRatings: 6,
    deliveriesCompleted: 7,
    requestsPosted: 5,
    totalEarnings: 590,
    badges: ['Campus Novice'],
    bookmarkedRequests: [],
    createdAt: '2024-06-20T10:40:00.000Z',
  },
];

export const INITIAL_REQUESTS = [
  {
    id: 'req-001',
    item: 'Casio fx-991EX ClassWiz Calculator',
    pickup: 'GEC Circle',
    dropoff: 'Shahid Tareq Huda Hall',
    reward: 100,
    urgency: 'High',
    details: 'Need it urgently for tomorrow morning semester final exam! Please buy from any stationary at GEC.',
    status: 'Open',
    requesterId: 'usr-102',
    requesterName: 'Abrar Zayad',
    acceptedById: null,
    acceptedByName: null,
    acceptedAt: null,
    inProgressAt: null,
    completedAt: null,
    paymentMethod: 'bKash',
    paymentStatus: 'Unpaid',
    rating: null,
    reportedBy: [],
    createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
  {
    id: 'req-002',
    item: 'Napa Extend & Entacyd Box (10 strips)',
    pickup: 'Pahartali',
    dropoff: 'Dr. Qudrat-E-Khuda Hall',
    reward: 60,
    urgency: 'High',
    details: 'Room 312. Feeling sick with fever, urgent help appreciated. Any pharmacy near Pahartali gate.',
    status: 'Accepted',
    requesterId: 'usr-101',
    requesterName: 'Tanvir Rahman',
    acceptedById: 'usr-103',
    acceptedByName: 'Nusrat Jahan',
    acceptedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    inProgressAt: null,
    completedAt: null,
    paymentMethod: 'bKash',
    paymentStatus: 'Unpaid',
    rating: null,
    reportedBy: [],
    createdAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: 'req-003',
    item: 'Architecture Drafting Sheet Roll & Markers',
    pickup: 'New Market, Chittagong',
    dropoff: 'Sufia Kamal Hall',
    reward: 120,
    urgency: 'Medium',
    details: '5 sheets of A1 Cartridge paper and Artline 0.5/0.8 fine liners from New Market art supplies.',
    status: 'InProgress',
    requesterId: 'usr-103',
    requesterName: 'Nusrat Jahan',
    acceptedById: 'usr-101',
    acceptedByName: 'Tanvir Rahman',
    acceptedAt: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
    inProgressAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    completedAt: null,
    paymentMethod: 'Nagad',
    paymentStatus: 'Unpaid',
    rating: null,
    reportedBy: [],
    createdAt: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
  },
  {
    id: 'req-004',
    item: 'Thesis Draft Spiral Binding (3 Copies)',
    pickup: 'Chawkbazar',
    dropoff: 'Shahid Abu Saeed Hall',
    reward: 150,
    urgency: 'Medium',
    details: 'Already printed at Nilkhet style printing press opposite Chittagong College. Just pick up the bound package.',
    status: 'Open',
    requesterId: 'usr-104',
    requesterName: 'Mahfuzur Rahman',
    acceptedById: null,
    acceptedByName: null,
    acceptedAt: null,
    inProgressAt: null,
    completedAt: null,
    paymentMethod: 'bKash',
    paymentStatus: 'Unpaid',
    rating: null,
    reportedBy: [],
    createdAt: new Date(Date.now() - 75 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 75 * 60 * 1000).toISOString(),
  },
  {
    id: 'req-005',
    item: 'Arduino Mega + Ultrasonic Sensors Kit',
    pickup: '2 No Gate',
    dropoff: 'Kabi Kazi Nazrul Islam Hall',
    reward: 80,
    urgency: 'Low',
    details: 'Packed in a small brown carton from ElectroTech shop, 2 No Gate. Pick up receipt on my name.',
    status: 'Open',
    requesterId: 'usr-105',
    requesterName: 'Samiul Alim',
    acceptedById: null,
    acceptedByName: null,
    acceptedAt: null,
    inProgressAt: null,
    completedAt: null,
    paymentMethod: 'Cash',
    paymentStatus: 'Unpaid',
    rating: null,
    reportedBy: [],
    createdAt: new Date(Date.now() - 180 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 180 * 60 * 1000).toISOString(),
  },
  {
    id: 'req-006',
    item: 'White Lab Coat (Size L) & Safety Goggles',
    pickup: 'Anderkilla',
    dropoff: 'Muktijoddha Hall',
    reward: 70,
    urgency: 'Medium',
    details: 'Needed for Thursday Organic Chemistry lab. Any pharmacy/uniform outlet in Anderkilla.',
    status: 'Completed',
    requesterId: 'usr-107',
    requesterName: 'Kazi Farhan',
    acceptedById: 'usr-102',
    acceptedByName: 'Abrar Zayad',
    acceptedAt: new Date(Date.now() - 360 * 60 * 1000).toISOString(),
    inProgressAt: new Date(Date.now() - 280 * 60 * 1000).toISOString(),
    completedAt: new Date(Date.now() - 200 * 60 * 1000).toISOString(),
    paymentMethod: 'bKash',
    paymentStatus: 'Paid',
    rating: 5.0,
    reportedBy: [],
    createdAt: new Date(Date.now() - 400 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 200 * 60 * 1000).toISOString(),
  },
  {
    id: 'req-007',
    item: 'Original Shwarma Box (4pcs) & Cold Coffee',
    pickup: 'GEC Circle',
    dropoff: 'Shahid Tareq Huda Hall',
    reward: 90,
    urgency: 'High',
    details: 'From Mehedibag / GEC foodie lane. Room 408. Will pay cash or bKash upon arrival!',
    status: 'Completed',
    requesterId: 'usr-102',
    requesterName: 'Abrar Zayad',
    acceptedById: 'usr-101',
    acceptedByName: 'Tanvir Rahman',
    acceptedAt: new Date(Date.now() - 720 * 60 * 1000).toISOString(),
    inProgressAt: new Date(Date.now() - 660 * 60 * 1000).toISOString(),
    completedAt: new Date(Date.now() - 600 * 60 * 1000).toISOString(),
    paymentMethod: 'Cash',
    paymentStatus: 'Paid',
    rating: 5.0,
    reportedBy: [],
    createdAt: new Date(Date.now() - 780 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 600 * 60 * 1000).toISOString(),
  },
  {
    id: 'req-008',
    item: 'Microbiology Practical Notebook (Classmate)',
    pickup: 'Muradpur',
    dropoff: 'Sufia Kamal Hall',
    reward: 50,
    urgency: 'Low',
    details: 'Single ruled practical bound notebook. Can be picked up from any stationery near Muradpur bus stand.',
    status: 'Open',
    requesterId: 'usr-106',
    requesterName: 'Sadia Afroz',
    acceptedById: null,
    acceptedByName: null,
    acceptedAt: null,
    inProgressAt: null,
    completedAt: null,
    paymentMethod: 'bKash',
    paymentStatus: 'Unpaid',
    rating: null,
    reportedBy: [],
    createdAt: new Date(Date.now() - 240 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 240 * 60 * 1000).toISOString(),
  },
];

export const INITIAL_MESSAGES = [
  {
    id: 'msg-001',
    requestId: 'req-002',
    senderId: 'usr-103',
    senderName: 'Nusrat Jahan',
    text: 'Hey Tanvir! I just accepted your medicine request. I am at Pahartali gate pharmacy right now.',
    createdAt: new Date(Date.now() - 28 * 60 * 1000).toISOString(),
  },
  {
    id: 'msg-002',
    requestId: 'req-002',
    senderId: 'usr-101',
    senderName: 'Tanvir Rahman',
    text: 'Thank you so much Nusrat! Please get Napa Extend if possible. Room 312 when you reach Q.K. Hall.',
    createdAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
  },
  {
    id: 'msg-003',
    requestId: 'req-002',
    senderId: 'usr-103',
    senderName: 'Nusrat Jahan',
    text: 'Got both Napa and Entacyd! Heading to campus on the 4:30 PM bus.',
    createdAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
  },
  {
    id: 'msg-004',
    requestId: 'req-003',
    senderId: 'usr-101',
    senderName: 'Tanvir Rahman',
    text: 'Hi Nusrat, I picked up your drafting sheets and Artline markers from New Market. Safely rolled with rubber bands!',
    createdAt: new Date(Date.now() - 22 * 60 * 1000).toISOString(),
  },
  {
    id: 'msg-005',
    requestId: 'req-003',
    senderId: 'usr-103',
    senderName: 'Nusrat Jahan',
    text: 'Awesome Tanvir! Call me when you are near the female hall security gate.',
    createdAt: new Date(Date.now() - 18 * 60 * 1000).toISOString(),
  },
];

export const INITIAL_NOTIFICATIONS = [
  {
    id: 'notif-001',
    userId: 'usr-101',
    text: 'Nusrat Jahan accepted your medicine request (Pahartali ➔ Q.K. Hall)!',
    read: false,
    requestId: 'req-002',
    type: 'request_accepted',
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-002',
    userId: 'usr-102',
    text: 'New delivery request posted in GEC Circle: Calculator needed urgently.',
    read: true,
    requestId: 'req-001',
    type: 'new_request',
    createdAt: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-003',
    userId: 'usr-101',
    text: 'You received a 5.0 rating and ৳90 reward for your delivery to Tareq Huda Hall! 🎉',
    read: true,
    requestId: 'req-007',
    type: 'rating_received',
    createdAt: new Date(Date.now() - 600 * 60 * 1000).toISOString(),
  },
];
